# Generated by Django 4.2.4 on 2023-08-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('MusicID', models.AutoField(primary_key=True, serialize=False)),
                ('MusicName', models.CharField(max_length=101)),
            ],
        ),
    ]
