# Generated by Django 4.2.4 on 2023-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MusicPlayerApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musics",
            name="MusicName",
            field=models.CharField(max_length=100),
        ),
    ]
