# Generated by Django 4.2.4 on 2023-08-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MusicPlayerApp", "0002_alter_musics_musicname"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("role", models.CharField(max_length=100)),
            ],
        ),
    ]
