# Generated by Django 4.2.4 on 2023-08-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayerApp', '0003_userrole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='MusicList',
        ),
        migrations.RenameField(
            model_name='musiclist',
            old_name='EmployeeId',
            new_name='MusicListId',
        ),
        migrations.RenameField(
            model_name='musiclist',
            old_name='EmployeeName',
            new_name='MusicListName',
        ),
        migrations.RenameField(
            model_name='musiclist',
            old_name='profile_pic',
            new_name='MusicListProfilePic',
        ),
    ]
