# Generated by Django 4.2.4 on 2023-08-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MusicPlayerApp", "0004_rename_employees_musiclist_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrole",
            old_name="username",
            new_name="userName",
        ),
        migrations.AddField(
            model_name="userrole",
            name="firstName",
            field=models.CharField(default="user", max_length=100),
        ),
        migrations.AddField(
            model_name="userrole",
            name="lastName",
            field=models.CharField(default="user", max_length=100),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
