# Generated by Django 4.2.4 on 2023-08-31 05:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "MusicPlayerApp",
            "0005_rename_username_userrole_username_userrole_firstname_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="userrole",
            old_name="userName",
            new_name="username",
        ),
    ]
