# Generated by Django 4.2.4 on 2023-09-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MusicPlayerApp", "0006_rename_username_userrole_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="musiclist",
            old_name="MusicListId",
            new_name="musicListId",
        ),
        migrations.RenameField(
            model_name="musiclist",
            old_name="MusicListProfilePic",
            new_name="musicListProfilePic",
        ),
        migrations.RenameField(
            model_name="musiclist",
            old_name="MusicListName",
            new_name="userBelongTo",
        ),
        migrations.RenameField(
            model_name="musics",
            old_name="MusicID",
            new_name="musicID",
        ),
        migrations.RenameField(
            model_name="musics",
            old_name="MusicName",
            new_name="musicName",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="firstName",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="userrole",
            old_name="lastName",
            new_name="lastname",
        ),
        migrations.AddField(
            model_name="musiclist",
            name="musicIn",
            field=models.ManyToManyField(to="MusicPlayerApp.musics"),
        ),
        migrations.AddField(
            model_name="musiclist",
            name="musicListName",
            field=models.CharField(default="favourite", max_length=100),
        ),
        migrations.AddField(
            model_name="musics",
            name="musicType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="musics",
            name="musicUrl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
