# Generated by Django 4.2.4 on 2023-10-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicPlayerApp', '0007_rename_musiclistid_musiclist_musiclistid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='musicListIn',
            field=models.ManyToManyField(to='MusicPlayerApp.musiclist'),
        ),
    ]
