# Generated by Django 4.2.4 on 2023-10-02 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MusicPlayerApp", "0008_userrole_musiclistin"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Musics",
            new_name="Music",
        ),
        migrations.RemoveField(
            model_name="userrole",
            name="musicListIn",
        ),
        migrations.AlterField(
            model_name="musiclist",
            name="userBelongTo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="music_lists",
                to="MusicPlayerApp.userrole",
            ),
        ),
    ]
