# Generated by Django 4.2.4 on 2023-10-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MusicPlayerApp", "0010_rename_musictype_music_musicauthor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musiclist",
            name="musicListProfilePic",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
